In [3]:
import torch

Creating a tensor

In [7]:
x = torch.empty(2,3,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

You can speficy Pytorch data types

In [10]:
x = torch.ones(2,2, dtype=torch.double)
print(x.dtype)

torch.float64


You can create tensors from Python lists

In [12]:
x = torch.tensor([2.5, 0.1])

Adding tensors

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)

y.add_(x)
print(y)

z = x + y
print(x)

a = x * y
print(a)

tensor([[0.5636, 1.1382],
        [1.3507, 1.4684]])
tensor([[0.4658, 0.8679],
        [0.7400, 0.8856]])
